application/urls.py
from django.urls import path
from .views import (
    home,
    about,
    contacts,
)

app_name = 'application'


urlpatterns = [
    path('', home, name='home'),
    path('home/', home, name='home'),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('application.urls', namespace='application.application'))
]

application/models.py
from django.db import models

# Create your models here.

application/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')
def about(request):
    return render(request, 'about.html')
def contacts(request):
    return render(request, 'contacts.html')
    

# Create your views here.

application/templates/about.html
{% extends 'layout/base.html' %}

{% block content %}
    <p class='about'><b>About us</b><br> ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam cumque eius veritatis. 
        Totam, enim. Sed nisi, ut inventore facere enim ullam unde, modi error quasi ipsa ratione, 
        porro sint minima. Fugit nobis expedita perspiciatis. Reiciendis repellat ab dolorum excepturi in, 
        mollitia distinctio sequi possimus ipsa necessitatibus asperiores voluptatem perferendis dolore dicta 
        aliquam ducimus non unde explicabo illo sunt, consequatur eos, consequuntur enim. Aut dicta culpa at
        luptas totam quasi rerum!</p>
{% endblock content %}

application/templates/contacts.html
{% extends 'layout/base.html' %}

{% block content %}
    <h3 class="contacts-title">contact us</h3>
    <div class="block">
        <img src="https://zeevector.com/wp-content/uploads/Phone-Icon-Vector-PNG.png" alt="">
        <a href="tel:+99890900000000">+99890 90 000 00 00</a>
    </div>
    <div class="block">
        <img src="https://zeevector.com/wp-content/uploads/Phone-Icon-Vector-PNG.png" alt="">
        <a href="tel:+99890900000000">+99890 90 123 45 67</a>
    </div>
{% endblock content %}

application/templates/home.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
    <div class="container flex-center">
        <img class="home-img" src="{% static 'media/home.svg' %}" alt="">
        <div class="container-right">
            <h1>Welcome to our <br> NoName group</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, voluptate.</p>
        </div>
    </div>
{% endblock content %}

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
</head>
<body>
    {% include '../layout/nav.html' %}

    {% block content %}
    {% endblock content %}
</body>
</html>

templates/layout/nav.html
<nav>
    <h3 class="logo-title">Какая то контора</h3>
    <a class='nav-a' href="{% url 'application:home'%}">Home</a>
    <a class='nav-a' href="{% url 'application:about'%}">About</a>
    <a class='nav-a' href="{% url 'application:contacts'%}">Contacts</a>
</nav>